// Network_internet_を開いて_Internet_が表示されることを.swift
// generated by ftester convert (from Network_internet_を開いて_Internet_が表示されることを.yaml)
// goal: 「Network & internet」を開いて、「Internet」が表示されることを確認する

import FTDSL

@TestClass(app: "com.android.settings", platform: "android")
class Network_internet_を開いて_Internet_が表示されることを {

    @Test("「Network & internet」を開いて、「Internet」が表示されることを確認する")
    func S0010() {
        scenario {
            scene(1) {
                condition {
                    launchApp()
                }.action {
                    tap("Network & internet||.Cell[3]")  // 「Network & internet」に移動するステップ1を実行する
                }.expectation {
                    exist("#collapsing_toolbar||Network & internet||.Other[2]")  // 目標から自動抽出した確認(探索終了時にコード側で検証済み)
                    exist("Internet||.Cell")  // 目標から自動抽出した確認(探索終了時にコード側で検証済み)
                }
            }
        }
    }
}
