// Flow(インメモリの内部モデル)→ Swift DSL シナリオコードの生成。gen-scenario(記録操作からのシナリオ生成)が使う。
// 生成コードは人が追記編集する前提の素直な直列コードにする。
//
// FTCore に居る理由: 入出力(Flow/FlowStep/FlowLocator/TestProject/ScenarioHost)は全て FTCore の型で、
// 生成先のコードが `import FTDSL` を書くだけ(このファイル自体は DSL ランタイムを呼ばない)。

import Foundation

public enum ScenarioCodeGen {

    /// Flow から @TestClass シナリオの .swift ソースを生成する
    /// `emptyExpectation` = アサーションが1件も無くても `.expectation { }` を空で出す。
    /// MCP の下書き(ft_draft_scenario)専用の形で、**推測でアサーションを作らない**ための入口:
    /// 空のまま出すと ft_dry_run の「アサーションの無い expectation ブロック」検出が
    /// 必ず作者に埋めさせる。dry-run が落ちるのは意図した設計(不具合として扱わない)
    /// `notesBeforeStep` = 「この手の**直前**に出すコメント行」(キーは `flow.steps` の 0 起点の位置。
    /// `steps.count` は末尾)。**位置を持つのが要点** —— MCP の下書きはセレクタを解決できなかった手を
    /// コメントで残すが、まとめて先頭へ出すと `action` の並びからその手が消え、
    /// 生成コードが実際の手順と食い違う(2026-08-10 に 33 手の下書きで実際に起きた)。
    ///
    /// `sceneBreaks` = 「ここから新しい scene」の位置(同じく 0 起点)。**推測はしない** ——
    /// シーン境界は「そのシーンで何を証明するか」という意図で、記録からは導けないので、
    /// 番号付き一覧を読んだ作者が指定する(`drop` と同じ流儀)。
    /// scene 2 以降は `condition` を出さない(launchApp は最初の1回だけ)
    public static func render(flow: Flow, className: String, generatedBy: String,
                              emptyExpectation: Bool = false,
                              notesBeforeStep: [Int: [String]] = [:],
                              sceneBreaks: [Int] = []) -> String {
        var lines: [String] = []
        lines.append("// \(className).swift")
        lines.append("// generated by \(generatedBy)")
        if let goal = flow.goal, !goal.isEmpty {
            lines.append("// goal: \(goal.replacingOccurrences(of: "\n", with: " "))")
        }
        if flow.dirty == true {
            lines.append("// TODO: generated while exploration was still incomplete — review before running")
        }
        lines.append("")
        lines.append("import FTDSL")
        lines.append("")

        var attr = "@TestClass(app: \(literal(flow.app))"
        if let platform = flow.platform { attr += ", platform: \(literal(platform))" }
        attr += ")"
        lines.append(attr)
        lines.append("class \(className) {")
        lines.append("")
        // @Test の説明文は flow.name を使う(gen-scenario が付けるシナリオ名)
        lines.append("    @Test(\(literal(flow.name)))")
        lines.append("    func \(methodName(1))() {")
        lines.append("        scenario {")

        let steps = flow.steps
        let indent = "                    "
        for (number, range) in sceneRanges(count: steps.count, breaks: sceneBreaks).enumerated() {
            // CAE 写像: launchApp → condition、末尾から連続する assert → expectation、残り → action
            var expectationStart = range.upperBound
            while expectationStart > range.lowerBound, steps[expectationStart - 1].assert != nil {
                expectationStart -= 1
            }
            let actionRange = range.lowerBound..<expectationStart
            let expectationRange = expectationStart..<range.upperBound

            // ブロックを組み立ててから繋ぐ。`condition{}.action{}.expectation{}` の連結は
            // 「2つ目以降だけ `}.` で始まる」形なので、先に中身を作らないと分岐が絡まる
            var blocks: [(name: String, body: [String])] = []
            // launchApp は最初の scene の condition だけ(2つ目以降で撃つと画面が巻き戻る)
            if number == 0 { blocks.append(("condition", [indent + "launchApp()"])) }
            var actionBody: [String] = []
            for index in actionRange {
                for note in notesBeforeStep[index] ?? [] { actionBody.append(indent + "// " + note) }
                actionBody.append(contentsOf: render(step: steps[index], indent: indent))
            }
            // 最後の手より後ろで解決できなかったものは、最後の scene の末尾に残す
            if range.upperBound == steps.count {
                for note in notesBeforeStep[steps.count] ?? [] { actionBody.append(indent + "// " + note) }
            }
            if !actionBody.isEmpty { blocks.append(("action", actionBody)) }
            var expectationBody = expectationRange.flatMap { render(step: steps[$0], indent: indent) }
            if expectationBody.isEmpty, emptyExpectation {
                expectationBody = [
                    indent + "// TODO: assert what this scenario is supposed to prove"
                        + " (e.g. textIs(\"…\") / exist(\"#id\")).",
                    indent + "// An empty expectation is intentional — ft_dry_run reports it"
                        + " so it cannot be forgotten.",
                ]
            }
            if !expectationBody.isEmpty { blocks.append(("expectation", expectationBody)) }

            lines.append("            scene(\(number + 1)) {")
            for (position, block) in blocks.enumerated() {
                lines.append(position == 0 ? "                \(block.name) {"
                                           : "                }.\(block.name) {")
                lines.append(contentsOf: block.body)
            }
            if !blocks.isEmpty { lines.append("                }") }
            lines.append("            }")
        }
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// 切れ目から scene の範囲を作る。**範囲外・重複・順不同を吸収する** ——
    /// 呼び出し側(MCP)は人が読んだ番号をそのまま渡してくるので、ここで正規化しないと
    /// 空の scene や逆転した範囲が出る。切れ目が無ければ 1 scene(従来どおり)
    static func sceneRanges(count: Int, breaks: [Int]) -> [Range<Int>] {
        guard count > 0 else { return [0..<0] }
        let starts = ([0] + breaks.filter { $0 > 0 && $0 < count }).sorted()
        var unique: [Int] = []
        for start in starts where unique.last != start { unique.append(start) }
        return unique.indices.map { unique[$0]..<($0 + 1 < unique.count ? unique[$0 + 1] : count) }
    }

    /// FlowStep → DSL コマンド行(+行末コメント)。行末コメントは FlowStep.note があるときのみ。
    /// 機械的な操作説明(StepDescription)は付けない(記録機能では note が無く、識別子から
    /// 自明な説明はコメント規約で不可のため)
    static func render(step: FlowStep, indent: String) -> [String] {
        guard var line = command(for: step) else {
            return [indent + "// (unsupported step: \(step.summary))"]
        }
        if let comment = step.note, !comment.isEmpty {
            line += "  // \(comment.replacingOccurrences(of: "\n", with: " "))"
        }
        return [indent + line]
    }

    static func command(for step: FlowStep) -> String? {
        let selector = selectorText(for: step)

        if let action = step.action {
            switch action {
            case "select":
                return "select(\(literal(selector))\(timeoutArg(step)))"
            case "tap":
                let hold = step.duration.map { ", holdSeconds: \(FTSeconds.format($0))" } ?? ""
                return "tap(\(literal(selector))\(hold))"
            case "type":
                let replaceArg = step.replace == true ? ", replace: true" : ""
                // ロケータなし = フォーカス中要素へ入力(直前の tap 前提)。type("text") を出す。
                if step.locator == nil {
                    return "type(\(literal(step.text ?? ""))\(replaceArg))"
                }
                return "type(\(literal(selector)), \(literal(step.text ?? ""))\(replaceArg))"
            case "swipe":
                return "swipe(.\(step.direction ?? "up"))"
            case "rotateTo":
                return "rotateTo(.\(step.direction ?? "landscape"))"
            case "home":
                return "home()"
            case "back":
                return "back()"
            case "hideKeyboard":
                return "hideKeyboard()"
            case "appSwitcher":
                return "appSwitcher()"
            case "terminate":
                return "terminateApp()"
            case "pressEnter":
                return "pressEnter()"
            case "openURL":
                // MCP の探索(ft_open_url)からの下書き用。DSL 側の openURL(url) と同じ形
                return "openURL(\(literal(step.text ?? "")))"
            case "press":
                // 長押しは tap の holdSeconds 引数で表す(DSL に別コマンドは無い)
                return "tap(\(literal(selector)), holdSeconds: \(FTSeconds.format(step.duration ?? 1.0)))"
            case "clearInput":
                if step.locator == nil {
                    return "clearInput()"
                }
                return "clearInput(\(literal(selector)))"
            case "doubleTap":
                return step.locator == nil ? "doubleTap()" : "doubleTap(\(literal(selector)))"
            case "pinchOut", "pinchIn":
                // 既定値は省く(生成コードを既定ケースで太らせない。tap の holdSeconds と同じ方針)
                let defaultScale = action == "pinchOut"
                    ? FlowStep.defaultPinchOutScale : FlowStep.defaultPinchInScale
                var args: [String] = step.locator == nil ? [] : [literal(selector)]
                if let scale = step.scale, scale != defaultScale {
                    args.append("scale: \(FTSeconds.format(scale))")
                }
                if let duration = step.duration {
                    args.append("durationSeconds: \(FTSeconds.format(duration))")
                }
                return "\(action)(\(args.joined(separator: ", ")))"
            case "swipeBy":
                var args: [String] = step.locator == nil ? [] : [literal(selector)]
                args.append("dxRatio: \(FTSeconds.format(step.dxRatio ?? 0))")
                args.append("dyRatio: \(FTSeconds.format(step.dyRatio ?? 0))")
                if let duration = step.duration {
                    args.append("durationSeconds: \(FTSeconds.format(duration))")
                }
                return "swipeBy(\(args.joined(separator: ", ")))"
            case "swipeElementToElement":
                guard let endLocator = step.endLocator else { return nil }
                var args = [literal(selector), literal(FTSelector.serialize(primary: endLocator, fallbacks: []))]
                if let duration = step.duration {
                    args.append("durationSeconds: \(FTSeconds.format(duration))")
                }
                return "swipeElementToElement(\(args.joined(separator: ", ")))"
            case "scroll":
                // ft_batch の scrollDown/Up/Left/Right と ft_swipe(scrollFrame 指定)の下書き用。
                // **これが無いと「通ったバッチは1:1でシナリオ行になる」という ft_batch の契約が破れる**
                // (scroll カテゴリは実行できるのに書き戻せない状態だった)。
                // FlowStep.direction は**指の動き**、DSL 名はコンテンツ基準なので写像して出す
                let finger = step.direction.flatMap(FTSwipeDirection.init(rawValue:)) ?? .up
                let content = FTScrollDirection.allCases.first { $0.swipe == finger } ?? .down
                var args = scrollFrameArgs(step)
                // maxSwipes は scroll では「繰り返し回数」(scrollImpl 参照)。既定 1 は書かない
                if let times = step.maxSwipes, times > 1 { args.append("repeat: \(times)") }
                return "scroll\(content.rawValue.capitalized)(\(args.joined(separator: ", ")))"
            case "scrollToEdge":
                // 名前はコンテンツ基準(scrollToEdgeImpl の表と同じ写像。片方だけ変えない)
                let finger = step.direction.flatMap(FTSwipeDirection.init(rawValue:)) ?? .up
                let content = FTScrollDirection.allCases.first { $0.swipe == finger } ?? .down
                let names: [FTScrollDirection: String] = [
                    .down: "scrollToBottom", .up: "scrollToTop",
                    .right: "scrollToRightEdge", .left: "scrollToLeftEdge",
                ]
                var args = scrollFrameArgs(step)
                // scrollToEdge の maxSwipes は暴走止めの上限。既定は書かない
                if let maxSwipes = step.maxSwipes, maxSwipes != FlowStep.defaultMaxEdgeSwipes {
                    args.append("maxSwipes: \(maxSwipes)")
                }
                return "\(names[content] ?? "scrollToBottom")(\(args.joined(separator: ", ")))"
            case "scrollTo":
                var args = [literal(selector)]
                // FlowStep.direction は**ジェスチャ(指の動き)**。DSL はコンテンツ基準なので写像して出す
                if let swipe = step.direction.flatMap(FTSwipeDirection.init(rawValue:)),
                   let scroll = FTScrollDirection.allCases.first(where: { $0.swipe == swipe }),
                   scroll != .down {
                    args.append("direction: .\(scroll.rawValue)")
                }
                args += scrollFrameArgs(step)
                if let maxSwipes = step.maxSwipes, maxSwipes != 8 {
                    args.append("maxSwipes: \(maxSwipes)")
                }
                return "scrollTo(\(args.joined(separator: ", ")))"
            default:
                return nil
            }
        }
        if let assert = step.assert {
            switch assert {
            case "exists":
                // exist は既定で可視性も確認。確認なし(occlusionGuard==false)は requireVisible: false
                let g = step.occlusionGuard == false ? ", requireVisible: false" : ""
                return "exist(\(literal(selector))\(timeoutArg(step))\(g))"
            case "valueEquals":
                let g = step.occlusionGuard == false ? ", requireVisible: false" : ""
                return "select(\(literal(selector))\(timeoutArg(step))\(g)).valueIs("
                    + "\(literal(step.expected ?? ""))\(timeoutArg(step))\(g))"
            case "textEquals":
                let g = step.occlusionGuard == false ? ", requireVisible: false" : ""
                return "select(\(literal(selector))\(timeoutArg(step))\(g)).textIs("
                    + "\(literal(step.expected ?? ""))\(timeoutArg(step))\(g))"
            case "notExists":
                // `exist` 側(exists ケース)はまだ scroll 再構成に未対応(別課題。exists は触らない)
                return "notExist(\(literal(selector))\(timeoutArg(step))\(notExistScrollArgs(step)))"
            case "enabled":
                return "select(\(literal(selector))\(timeoutArg(step))).enabledIsTrue(\(bareTimeoutArg(step)))"
            case "disabled":
                return "select(\(literal(selector))\(timeoutArg(step))).enabledIsFalse(\(bareTimeoutArg(step)))"
            case "count":
                return "countIs(\(literal(selector)), \(step.expectedCount ?? 0)\(timeoutArg(step)))"
            case "screenMatches":
                return "screenIs(\(literal(step.expected ?? "")))"
            case "keyboardShown":
                return "keyboardIsShown(\(bareTimeoutArg(step)))"
            case "keyboardNotShown":
                return "keyboardIsNotShown(\(bareTimeoutArg(step)))"
            default:
                return nil
            }
        }
        return nil
    }

    /// `notExist(scroll:)` 生成用: FlowStep.direction(**ジェスチャ**)を FTScrollDirection へ逆写像し、
    /// `scroll:`/`maxSwipes:` 引数を再構成する。scrollTo ケースの写像と同じ規則だが、notExist の
    /// scroll 既定は「探索しない」(nil)なので scrollTo と違い `.down` を特別扱いしない
    private static func notExistScrollArgs(_ step: FlowStep) -> String {
        guard let swipe = step.direction.flatMap(FTSwipeDirection.init(rawValue:)),
              let scroll = FTScrollDirection.allCases.first(where: { $0.swipe == swipe }) else {
            return ""
        }
        var args = ", scroll: .\(scroll.rawValue)"
        for arg in scrollFrameArgs(step) { args += ", " + arg }
        if let maxSwipes = step.maxSwipes, maxSwipes != FlowStep.defaultMaxSwipes {
            args += ", maxSwipes: \(maxSwipes)"
        }
        return args
    }

    /// `scrollFrame:` とマージンを DSL 引数へ戻す。**落とすと往復で領域指定が消え、
    /// 黙って全画面スワイプに戻る**(生成コードは実行と同じ意味でなければならない)
    static func scrollFrameArgs(_ step: FlowStep) -> [String] {
        var args: [String] = []
        if let frame = step.scrollFrame {
            args.append("scrollFrame: \(literal(FTSelector.serialize(primary: frame, fallbacks: [])))")
        }
        if let ratio = step.startMarginRatio {
            args.append("startMarginRatio: \(ratio)")
        }
        if let ratio = step.endMarginRatio {
            args.append("endMarginRatio: \(ratio)")
        }
        return args
    }

    /// timeoutArg は「他の引数の後に続ける」前提で先頭カンマを持つ。keyboardIsShown/
    /// keyboardIsNotShown は timeout が唯一の引数なので、その場合だけカンマを落とす
    private static func bareTimeoutArg(_ step: FlowStep) -> String {
        let arg = timeoutArg(step)
        return arg.isEmpty ? "" : String(arg.dropFirst(2))
    }

    static func selectorText(for step: FlowStep) -> String {
        guard let primary = step.locator else { return "" }
        return FTSelector.serialize(primary: primary, fallbacks: step.fallbacks ?? [])
    }

    static func timeoutArg(_ step: FlowStep) -> String {
        if let timeout = step.timeout, timeout != 5 { return ", timeout: \(FTSeconds.format(timeout))" }
        return ""
    }

    /// Swift 文字列リテラルとしてエスケープする(日本語はそのまま)。
    /// public: ScenarioDraftCodeGen.literal(FTDSL)がそのまま転送する
    public static func literal(_ text: String) -> String {
        var escaped = ""
        for ch in text {
            switch ch {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\t": escaped += "\\t"
            default: escaped.append(ch)
            }
        }
        return "\"\(escaped)\""
    }

    /// 生成メソッド名(連番: S0010, S0020, …)
    public static func methodName(_ ordinal: Int) -> String {
        String(format: "S%04d", ordinal * 10)
    }

    /// 書き込んでビルド検証し、失敗時は quarantineDir へ隔離して throw する
    /// (1 つの生成不良がシナリオスイート全体を道連れにしないため)
    @discardableResult
    public static func writeValidated(code: String, className: String,
                                      dir: URL, quarantineDir: URL,
                                      project: TestProject) throws -> URL {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("\(className).swift")
        try code.write(to: url, atomically: true, encoding: .utf8)
        do {
            try ScenarioHost.build(project: project)
        } catch {
            try? FileManager.default.createDirectory(at: quarantineDir, withIntermediateDirectories: true)
            let quarantined = quarantineDir.appendingPathComponent("\(className).swift")
            try? FileManager.default.moveItem(at: url, to: quarantined)
            // 隔離後はスイートが再びビルドできることを確認しておく(失敗しても実行時に分かる)
            try? ScenarioHost.build(project: project)
            throw CodeGenError.buildFailed(quarantined: quarantined,
                                           detail: error.localizedDescription)
        }
        return url
    }

    public enum CodeGenError: Error, LocalizedError {
        case buildFailed(quarantined: URL, detail: String)

        public var errorDescription: String? {
            switch self {
            case .buildFailed(let quarantined, let detail):
                return "the generated code failed to build and was quarantined to \(quarantined.path).\n\(detail)"
            }
        }
    }

    /// 生成先の既存クラス名(.swift ベース名)を収集する(重複回避用)。
    /// シナリオはフォルダ(scenarios/ 直下 1 階層)にも置けるため、サブディレクトリも見る
    public static func existingClassNames(in dirs: [URL]) -> Set<String> {
        var names = Set<String>()
        for dir in dirs {
            let entries = (try? FileManager.default.contentsOfDirectory(
                at: dir, includingPropertiesForKeys: [.isDirectoryKey])) ?? []
            for entry in entries {
                if entry.pathExtension == "swift" {
                    names.insert(entry.deletingPathExtension().lastPathComponent)
                } else if (try? entry.resourceValues(forKeys: [.isDirectoryKey]).isDirectory)
                    == true {
                    let inner = (try? FileManager.default.contentsOfDirectory(
                        at: entry, includingPropertiesForKeys: nil)) ?? []
                    for file in inner where file.pathExtension == "swift" {
                        names.insert(file.deletingPathExtension().lastPathComponent)
                    }
                }
            }
        }
        return names
    }

    /// フロー名から Swift クラス名を作る(日本語可・数字始まり回避・重複時 _2)
    public static func suggestedClassName(for flow: Flow, existing: Set<String> = []) -> String {
        suggestedClassName(fromName: flow.name, existing: existing)
    }

    /// 生の名前文字列から Swift クラス名を作る(record 経路は FM のシンプル名を直接渡す)
    public static func suggestedClassName(fromName rawName: String, existing: Set<String> = []) -> String {
        var sanitized = ""
        for scalar in rawName.unicodeScalars {
            if CharacterSet.alphanumerics.contains(scalar) ||
               scalar.properties.isIdeographic ||
               (0x3040...0x30FF).contains(Int(scalar.value)) {  // ひらがな・カタカナ
                sanitized.unicodeScalars.append(scalar)
            } else {
                sanitized.append("_")
            }
        }
        while sanitized.contains("__") {
            sanitized = sanitized.replacingOccurrences(of: "__", with: "_")
        }
        var base = String(sanitized.trimmingCharacters(in: CharacterSet(charactersIn: "_")).prefix(40))
        if base.isEmpty { base = "シナリオ" }
        if let first = base.unicodeScalars.first, CharacterSet.decimalDigits.contains(first) {
            base = "_" + base
        }
        var name = base
        var counter = 2
        while existing.contains(name) {
            name = "\(base)_\(counter)"
            counter += 1
        }
        return name
    }
}
