// ログイン画面のテスト.swift
// generated by ftester record v0.1

import FTDSL

@TestClass(app: "com.example.sampleapp", platform: "ios")
class ログイン画面のテスト {

    @Test("メールアドレスを入力してログインボタンを押すテストを行う")
    func S0010() {
        scenario {
            scene(1) {
                condition {
                    launchApp()
                }.action {
                    tap("#email")
                    type("あ")
                    tap("#login_btn||ログイン")
                }
            }
        }
    }
}
