// ScenarioDraft(テストベース由来の自然言語手順)→ Swift DSL シナリオの**下書き**生成。
// 記録操作からの生成(ScenarioCodeGen)は実セレクタを持つが、こちらは持たないので
// セレクタは全て TODO プレースホルダになる。
//
// 設計上の要点(壊さないこと):
// - 生成クラスには @Deleted を付ける。下書きは一括実行から外れる(が一覧には残る)。
//   人が TODO を実セレクタへ置き換えてから @Deleted を外す運用。
// - プレースホルダは `#TODO` = 決して解決できない id。埋め忘れたまま @Deleted を外すと
//   「ロケータを解決できません」で**確実に落ちる**(空実装で緑になる方が危険なので意図的)。
// - 手順文はコマンド行の末尾コメントに必ず残す(FM/パーサの写像が外れても情報は失われない)。

import Foundation
import FTCore

public enum ScenarioDraftCodeGen {

    /// 実セレクタが決まっていないことを示すプレースホルダ(解決不能な id)
    public static let placeholder = "#TODO"

    /// app: nil = `@TestClass(app:)` を書かない(実行プロファイルから解決させる)。
    /// **アプリプロファイルから導いた値のときは nil を渡す** —— 同じ値を写しても意味が無く、
    /// 別ビルドのプロファイルへ差し替えたときにコード側が黙って勝ってしまう。
    /// 利用者が `--app` で明示した値だけは、書き手の意図として残す
    public static func render(draft: ScenarioDraft, className: String, app: String?,
                              platform: String?, source: String, generatedBy: String) -> String {
        var lines: [String] = []
        lines.append("// \(className).swift")
        lines.append("// generated by \(generatedBy)")
        lines.append("// testbase: \(source)")
        lines.append("// Draft: selectors are still \(placeholder). Capture real selectors from a device snapshot,")
        lines.append("//        then remove the class's @Deleted once it works (excluded from bulk runs until then).")
        lines.append("")
        lines.append("import FTDSL")
        lines.append("")

        var parts: [String] = []
        if let app, !app.isEmpty { parts.append("app: \(literal(app))") }
        if let platform, !platform.isEmpty { parts.append("platform: \(literal(platform))") }
        lines.append(parts.isEmpty ? "@TestClass" : "@TestClass(\(parts.joined(separator: ", ")))")
        lines.append("@Deleted(\"draft — delete this line once \(placeholder) is replaced with real selectors\")")
        lines.append("class \(className) {")
        lines.append("")
        lines.append("    @Test(\(literal(draft.title)))")
        lines.append("    func \(ScenarioCodeGen.methodName(1))() {")
        lines.append("        scenario {")

        for (index, scene) in draft.scenes.enumerated() {
            lines.append(contentsOf: render(scene: scene, isFirst: index == 0))
        }

        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    static func render(scene: DraftScene, isFirst: Bool) -> [String] {
        let indent = "                    "
        var lines: [String] = []
        lines.append("            scene(\(scene.number), \(literal(scene.title))) {")

        var conditionLines = scene.condition.map { commandLine(forCondition: $0, indent: indent) }
        // 最初の scene は起動から始める。2 番目以降は前の scene の状態を引き継ぐのが普通なので足さない
        if isFirst, !conditionLines.contains(where: { $0.contains("launchApp()") }) {
            conditionLines.insert(indent + "launchApp()", at: 0)
        }
        if conditionLines.isEmpty { conditionLines = [indent + "// (no preconditions)"] }
        lines.append("                condition {")
        lines.append(contentsOf: conditionLines)

        let closing = "                }"
        if !scene.action.isEmpty {
            lines.append(closing + ".action {")
            lines.append(contentsOf: scene.action.map { commandLine(forAction: $0, indent: indent) })
        }
        if !scene.expectation.isEmpty {
            lines.append(closing + ".expectation {")
            lines.append(contentsOf: scene.expectation.map {
                commandLine(forExpectation: $0, indent: indent)
            })
        }
        lines.append(closing)
        lines.append("            }")
        return lines
    }

    // MARK: - 自然言語 → コマンド候補
    //
    // 「だいたい合っている雛形」を出すのが目的で、正確さは求めない(どうせ人が直す)。
    // 判定は日本語の語尾・語彙の単純な包含判定のみ(FM はここでは使わない = 生成が決定的になる)。

    static func commandLine(forCondition text: String, indent: String) -> String {
        let comment = trailingComment(text)
        if isAppLaunch(text) {
            return indent + "launchApp()\(comment)"
        }
        // 前提はデータ投入・状態準備が多くコマンド化できない。手順文をコメントで残す
        return indent + "// TODO: prepare the precondition 「\(inline(text))」 (e.g. seed data via procedure { })"
    }

    /// 「アプリの起動」を指す前提か。**「開く」「表示する」だけでは起動と見なさない** —
    /// 「カートタブを開く」のような画面内操作まで launchApp() に化けるため
    /// (FM 経路の実出力で確認。2026-07-26)。目的語がアプリのときだけ「開く」を起動と読む。
    static func isAppLaunch(_ text: String) -> Bool {
        if contains(text, ["起動", "立ち上げ", "launch"]) { return true }
        return contains(text, ["アプリ", "app"]) && contains(text, ["開く", "表示"])
    }

    static func commandLine(forAction text: String, indent: String) -> String {
        let comment = trailingComment(text)
        if contains(text, ["入力", "記入", "打ち込", "type"]) {
            return indent + "type(\(literal(placeholder)), \"TODO\")\(comment)"
        }
        if contains(text, ["長押し", "ロングタップ"]) {
            return indent + "tap(\(literal(placeholder)), holdSeconds: 1)\(comment)"
        }
        if contains(text, ["スクロール", "スワイプ", "swipe", "scroll"]) {
            return indent + "scrollTo(\(literal(placeholder)))\(comment)"
        }
        if contains(text, ["再起動", "起動し直"]) {
            return indent + "restartApp()\(comment)"
        }
        if contains(text, ["起動", "launch"]) {
            return indent + "launchApp()\(comment)"
        }
        if contains(text, ["待", "wait"]) {
            return indent + "wait(1)\(comment)"
        }
        return indent + "tap(\(literal(placeholder)))\(comment)"
    }

    static func commandLine(forExpectation text: String, indent: String) -> String {
        let comment = trailingComment(text)
        if contains(text, ["表示されない", "表示しない", "消え", "閉じ", "非表示", "現れない"]) {
            return indent + "notExist(\(literal(placeholder)))\(comment)"
        }
        if contains(text, ["押せない", "操作できない", "無効", "タップできない", "disabled"]) {
            return indent + "select(\(literal(placeholder))).enabledIsFalse()\(comment)"
        }
        if contains(text, ["押せる", "操作できる", "有効", "enabled"]) {
            return indent + "select(\(literal(placeholder))).enabledIsTrue()\(comment)"
        }
        if let count = itemCount(in: text) {
            return indent + "countIs(\(literal(placeholder)), \(count))\(comment)"
        }
        if contains(text, ["と表示", "というテキスト", "文言", "メッセージ"]) {
            return indent + "select(\(literal(placeholder))).textIs(\"TODO\")\(comment)"
        }
        return indent + "exist(\(literal(placeholder)))\(comment)"
    }

    /// 「3件」「5 個」「2 行」から個数を読む(countIs の雛形用)。無ければ nil
    static func itemCount(in text: String) -> Int? {
        guard let range = text.range(of: #"(\d+)\s*(件|個|行|項目)"#, options: .regularExpression),
              let digits = text[range].range(of: #"\d+"#, options: .regularExpression) else {
            return nil
        }
        return Int(text[digits])
    }

    static func contains(_ text: String, _ keywords: [String]) -> Bool {
        let lowered = text.lowercased()
        return keywords.contains { lowered.contains($0.lowercased()) }
    }

    /// 手順文を必ずコマンド行に残す(写像が外れても元の意図が読める)
    static func trailingComment(_ text: String) -> String {
        "  // \(inline(text))"
    }

    static func inline(_ text: String) -> String {
        text.replacingOccurrences(of: "\n", with: " ")
    }

    static func literal(_ text: String) -> String { ScenarioCodeGen.literal(text) }
}
