// Flow(インメモリの内部モデル)→ Swift DSL シナリオコードの生成。explore(FM 探索)が使う。
// 生成コードは人が追記編集する前提の素直な直列コードにする。

import Foundation
import FTCore

public enum ScenarioCodeGen {

    /// Flow から @TestClass シナリオの .swift ソースを生成する
    public static func render(flow: Flow, className: String, generatedBy: String) -> String {
        var lines: [String] = []
        lines.append("// \(className).swift")
        lines.append("// generated by \(generatedBy)")
        if let goal = flow.goal, !goal.isEmpty {
            lines.append("// goal: \(goal.replacingOccurrences(of: "\n", with: " "))")
        }
        if flow.dirty == true {
            lines.append("// TODO: 探索が未完了のまま生成されています。手直ししてから実行してください")
        }
        lines.append("")
        lines.append("import FTDSL")
        lines.append("")

        var attr = "@TestClass(app: \(literal(flow.app))"
        if let platform = flow.platform { attr += ", platform: \(literal(platform))" }
        attr += ")"
        lines.append(attr)
        lines.append("class \(className) {")
        lines.append("")
        // @Test の説明文は flow.name を使う(record 経路=FM 操作要約 / explore 経路=シナリオ名)
        lines.append("    @Test(\(literal(flow.name)))")
        lines.append("    func \(methodName(1))() {")
        lines.append("        scenario {")
        lines.append("            scene(1) {")

        // CAE 写像: launchApp → condition、末尾から連続する assert → expectation、残り → action
        let steps = flow.steps
        var expectationStart = steps.count
        while expectationStart > 0, steps[expectationStart - 1].assert != nil {
            expectationStart -= 1
        }
        let actionSteps = Array(steps[..<expectationStart])
        let expectationSteps = Array(steps[expectationStart...])

        let indent = "                    "
        lines.append("                condition {")
        lines.append(indent + "launchApp()")
        var closing = "                }"
        if !actionSteps.isEmpty {
            lines.append(closing + ".action {")
            for step in actionSteps { lines.append(contentsOf: render(step: step, indent: indent)) }
        }
        if !expectationSteps.isEmpty {
            lines.append(closing + ".expectation {")
            for step in expectationSteps { lines.append(contentsOf: render(step: step, indent: indent)) }
        }
        lines.append(closing)

        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// FlowStep → DSL コマンド行(+行末コメント)。コメントは FM の意図メモ(note)のみ。
    /// 機械的な操作説明(StepDescription)は付けない(記録機能では note が無く、識別子から
    /// 自明な説明はコメント規約で不可のため。explore は FM が note を入れるので残る)
    static func render(step: FlowStep, indent: String) -> [String] {
        guard var line = command(for: step) else {
            return [indent + "// (未対応ステップ: \(step.summary))"]
        }
        if let comment = step.note, !comment.isEmpty {
            line += "  // \(comment.replacingOccurrences(of: "\n", with: " "))"
        }
        return [indent + line]
    }

    static func command(for step: FlowStep) -> String? {
        let selector = selectorText(for: step)

        if let action = step.action {
            switch action {
            case "tap":
                return "tap(\(literal(selector))\(optionalArg(step)))"
            case "type":
                return "type(\(literal(selector)), \(literal(step.text ?? ""))\(optionalArg(step)))"
            case "press":
                return "press(\(literal(selector)))"
            case "swipe":
                return "swipe(.\(step.direction ?? "up"))"
            case "home":
                return "home()"
            case "appSwitcher":
                return "appSwitcher()"
            case "terminate":
                return "terminateApp()"
            case "scrollTo":
                var args = [literal(selector)]
                if let direction = step.direction, direction != "up" {
                    args.append("direction: .\(direction)")
                }
                if let maxSwipes = step.maxSwipes, maxSwipes != 8 {
                    args.append("maxSwipes: \(maxSwipes)")
                }
                return "scrollTo(\(args.joined(separator: ", ")))"
            default:
                return nil
            }
        }
        if let assert = step.assert {
            switch assert {
            case "exists":
                return "exist(\(literal(selector))\(timeoutArg(step)))"
            case "valueEquals":
                return "valueIs(\(literal(selector)), \(literal(step.expected ?? ""))\(timeoutArg(step)))"
            case "textEquals":
                return "textIs(\(literal(selector)), \(literal(step.expected ?? ""))\(timeoutArg(step)))"
            case "screenMatches":
                return "screenIs(\(literal(step.expected ?? "")))"
            default:
                return nil
            }
        }
        return nil
    }

    static func selectorText(for step: FlowStep) -> String {
        guard let primary = step.locator else { return "" }
        return FTSelector.serialize(primary: primary, fallbacks: step.fallbacks ?? [])
    }

    static func optionalArg(_ step: FlowStep) -> String {
        step.optional == true ? ", optional: true" : ""
    }

    static func timeoutArg(_ step: FlowStep) -> String {
        if let timeout = step.timeout, timeout != 5 { return ", timeout: \(timeout)" }
        return ""
    }

    /// Swift 文字列リテラルとしてエスケープする(日本語はそのまま)
    static func literal(_ text: String) -> String {
        var escaped = ""
        for ch in text {
            switch ch {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\t": escaped += "\\t"
            default: escaped.append(ch)
            }
        }
        return "\"\(escaped)\""
    }

    /// 生成メソッド名(連番: S0010, S0020, …)
    public static func methodName(_ ordinal: Int) -> String {
        String(format: "S%04d", ordinal * 10)
    }

    /// 書き込んでビルド検証し、失敗時は quarantineDir へ隔離して throw する
    /// (1 つの生成不良がシナリオスイート全体を道連れにしないため)
    @discardableResult
    public static func writeValidated(code: String, className: String,
                                      dir: URL, quarantineDir: URL,
                                      project: TestProject) throws -> URL {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("\(className).swift")
        try code.write(to: url, atomically: true, encoding: .utf8)
        do {
            try ScenarioHost.build(project: project)
        } catch {
            try? FileManager.default.createDirectory(at: quarantineDir, withIntermediateDirectories: true)
            let quarantined = quarantineDir.appendingPathComponent("\(className).swift")
            try? FileManager.default.moveItem(at: url, to: quarantined)
            // 隔離後はスイートが再びビルドできることを確認しておく(失敗しても実行時に分かる)
            try? ScenarioHost.build(project: project)
            throw CodeGenError.buildFailed(quarantined: quarantined,
                                           detail: error.localizedDescription)
        }
        return url
    }

    public enum CodeGenError: Error, LocalizedError {
        case buildFailed(quarantined: URL, detail: String)

        public var errorDescription: String? {
            switch self {
            case .buildFailed(let quarantined, let detail):
                return "生成コードのビルドに失敗したため \(quarantined.path) に隔離しました。\n\(detail)"
            }
        }
    }

    /// 生成先の既存クラス名(.swift ベース名)を収集する(重複回避用)。
    /// シナリオはフォルダ(Scenarios/ 直下 1 階層)にも置けるため、サブディレクトリも見る
    public static func existingClassNames(in dirs: [URL]) -> Set<String> {
        var names = Set<String>()
        for dir in dirs {
            let entries = (try? FileManager.default.contentsOfDirectory(
                at: dir, includingPropertiesForKeys: [.isDirectoryKey])) ?? []
            for entry in entries {
                if entry.pathExtension == "swift" {
                    names.insert(entry.deletingPathExtension().lastPathComponent)
                } else if (try? entry.resourceValues(forKeys: [.isDirectoryKey]).isDirectory)
                    == true {
                    let inner = (try? FileManager.default.contentsOfDirectory(
                        at: entry, includingPropertiesForKeys: nil)) ?? []
                    for file in inner where file.pathExtension == "swift" {
                        names.insert(file.deletingPathExtension().lastPathComponent)
                    }
                }
            }
        }
        return names
    }

    /// フロー名から Swift クラス名を作る(日本語可・数字始まり回避・重複時 _2)
    public static func suggestedClassName(for flow: Flow, existing: Set<String> = []) -> String {
        suggestedClassName(fromName: flow.name, existing: existing)
    }

    /// 生の名前文字列から Swift クラス名を作る(record 経路は FM のシンプル名を直接渡す)
    public static func suggestedClassName(fromName rawName: String, existing: Set<String> = []) -> String {
        var sanitized = ""
        for scalar in rawName.unicodeScalars {
            if CharacterSet.alphanumerics.contains(scalar) ||
               scalar.properties.isIdeographic ||
               (0x3040...0x30FF).contains(Int(scalar.value)) {  // ひらがな・カタカナ
                sanitized.unicodeScalars.append(scalar)
            } else {
                sanitized.append("_")
            }
        }
        while sanitized.contains("__") {
            sanitized = sanitized.replacingOccurrences(of: "__", with: "_")
        }
        var base = String(sanitized.trimmingCharacters(in: CharacterSet(charactersIn: "_")).prefix(40))
        if base.isEmpty { base = "シナリオ" }
        if let first = base.unicodeScalars.first, CharacterSet.decimalDigits.contains(first) {
            base = "_" + base
        }
        var name = base
        var counter = 2
        while existing.contains(name) {
            name = "\(base)_\(counter)"
            counter += 1
        }
        return name
    }
}
