// ネットワーク設定_並列テスト_08.swift
// generated by ftester convert (from android-parallel-08.yaml)
// goal: 「Network & internet」を開いて、「Internet」が表示されることを確認する

import FTDSL

@TestClass(app: "com.android.settings", platform: "android")
class ネットワーク設定_並列テスト_08 {

    @Test("ネットワーク設定 並列テスト 08")
    func S0010() {
        scenario {
            scene(1) {
                condition {
                    launchApp()
                }.action {
                    tap("Network & internet||.Cell[3]")  // 「Network & internet」に移動するステップ1を実行する
                }.expectation {
                    exist("#collapsing_toolbar||Network & internet||.Other[2]")  // 目標から自動抽出した確認(探索終了時にコード側で検証済み)
                    exist("Internet||.Cell")  // 目標から自動抽出した確認(探索終了時にコード側で検証済み)
                }
            }
        }
    }
}
