// Resource_Upload_Test_Mode_が_ON_であること.swift
// generated by ftester convert (from resource-upload-test-mode.yaml)
// goal: 設定 > デベロッパ > Photos > Resource Upload Test Mode のスイッチが ON なら OK、OFF なら NG

import FTDSL

// 注意: このシナリオはデバイスのトグル実状態に依存する(iPhone 17 Pro は ON 設定済み。
// iPhone Air 等 OFF のデバイスに分配されると NG になる)。並列実行から外す場合は
// Scenarios/_disabled/ へ移動する。
@TestClass(app: "com.apple.Preferences", platform: "ios")
class iOS設定のデバイス画面 {

    @Test("Resource Upload Test Mode が ON であること")
    func S0010() {
        scenario {
            scene(1) {
                condition {
                    launchApp()
                }.action {
                    scrollTo("#com.apple.settings.developer||デベロッパ||Developer")  // 設定トップを下へスクロールして「デベロッパ」行を探す
                    tap("#com.apple.settings.developer||デベロッパ||Developer")
                    scrollTo(".Switch#PHOTOS_UPLOAD_DEVELOPER_MODE||.Switch=Resource Upload Test Mode", maxSwipes: 12)  // デベロッパ画面を下へスクロールして Photos セクションのスイッチを探す
                }.expectation {
                    valueIs(".Switch#PHOTOS_UPLOAD_DEVELOPER_MODE||.Switch=Resource Upload Test Mode", "1")  // スイッチの value が "1"(ON)なら OK、"0"(OFF)なら NG
                }
            }
        }
    }
}
