export type RootStackParamList = {
  Home: undefined;
  Pager: undefined;
  Sheet: undefined;
  Menu: undefined;
  DatePicker: undefined;
  Drawer: undefined;
  Refresh: undefined;
  Snackbar: undefined;
  Grid: undefined;
  Swipe: undefined;
  Tabs: undefined;
  Anim: undefined;
  Tooltip: undefined;
  Chips: undefined;
  Search: undefined;
  ArgNav: undefined;
  Detail: { id: number };
  Collapse: undefined;
  Sticky: undefined;
  Time: undefined;
  Dialogs: undefined;
  Context: undefined;
  Reorder: undefined;
  Inputs: undefined;
  Fab: undefined;
  Expand: undefined;
  Stepper: undefined;
  Infinite: undefined;
  Zoom: undefined;
  Native: undefined;
};
