// Network_internet_を開いて_Internet_が表示されることを.swift
// generated by ftester convert (from Network_internet_を開いて_Internet_が表示されることを.yaml)
// goal: 「Network & internet」を開いて、「Internet」が表示されることを確認する

import FTDSL

@TestClass(app: "com.android.settings", platform: "android")
class Android設定アプリ {

    @Test("「Network & internet」を開いて、「Internet」が表示されることを確認する")
    func S0010() {
        scenario {
            scene(1) {
                condition {
                    launchApp()
                }.action {
                    tap("ネットワークとインターネット")  // 「Network & internet」に移動するステップ1を実行する
                }.expectation {
                    exist("#collapsing_toolbar||Network & internet")  // 目標から自動抽出した確認(探索終了時にコード側で検証済み)
                    exist("Internet||インターネット")  // 「Internet」項目の表示確認(英語/日本語ロケール両対応)
                }
            }
        }
    }
}
